 classDiagram
      User -- Profile
      User --|> Post
      User --|> Comment
      Post --|> Comment
      class Profile{
         
      }
      class Post{
        
      }
      class Comment{
        
      }
